### ISSUE TITLE
Typo in welcome page

### ISSUE THREAD

**Issue by shagn** [VincentMeilinger/Nextcloud-Cookbook-iOS#1]
In the English landing page it says 'Tank you...' instead of 'Thank you...'

![image](https://github.com/VincentMeilinger/Nextcloud-Cookbook-iOS/assets/16029092/ca550ca9-e249-4dfb-bd4e-86c7d1577403)

**Comment by VincentMeilinger** [comment]
Hey @shagn, thank you for pointing this out! It's fixed now and will be part of one of the next updates.
