### ISSUE TITLE
Connect to server via http

### ISSUE THREAD

**Issue by riemnafets** [VincentMeilinger/Nextcloud-Cookbook-iOS#13]
For LAN-only Nextcloud instances (like mine) the app should permit to connect via http and not enforce https. Currently (v1.6) it fully fails to connect via http and there does not seem to be any syntax in the server address field that allows using http.
Suggestion: let us put `http://<hostname>:<port>` in the server address field (like most other apps in the Nextcloud ecosystem do it).

**Comment by VincentMeilinger** [comment]
Hello @riemnafets,
I appreciate you highlighting this issue – it's a use case that hadn't occurred to me before! I plan to address it in the upcoming weeks and will definitely keep you updated on the release.

**Comment by VincentMeilinger** [comment]
Hey @riemnafets, 
You suggestion is now implemented and I'm currently testing it. You can expect the update on the App Store next week.

**Comment by riemnafets** [comment]
Dear @VincentMeilinger ,
I very much appreciate your work on this and it looks like exactly what I suggested. However, I absolutely cannot get it to run:
I have version 1.8.1 running, select “http” in the login screen and enter my server's address + port, but all I get is:
“Unable to reach server. Please check your server address and internet connection.”
<img src="https://github.com/VincentMeilinger/Nextcloud-Cookbook-iOS/assets/44099882/c7d7bfed-6924-40da-9738-4016f83f55ad" width="400">
I've tried all variants of the server address that I can come up with (including the plain IP address, omitting the `fritz.box` domain), all of which are properly resolved in Safari, but none of which work here.

I have also tried anything I can come with in the “App Token Login” screen, only to get a slightly different error message saying “Login failed. Please check your inputs.”

I have also tried connecting to some other Nextcloud installation that I have access to and which does support https. That server has not installed the cookbook app, so I would not expect your app to work, but at least in this case I can get to the login screen in the in-app browser.

**Comment by VincentMeilinger** [comment]
Hey, I'm sorry for not letting you know, but there is a small bug at the moment that prevents you from using http servers. I'm in the process of fixing this, it should not take too long ;)

**Comment by VincentMeilinger** [comment]
I uploaded a new version to the app store (v1.8.2), which should fix your problem. It may require a day or two for the AppStore team to approve the update. Once it's available, I would appreciate your feedback whether it works for you or not!

**Comment by VincentMeilinger** [comment]
Hey @riemnafets,
Could you download the update and try if the login works for you? 
Unfortunately I introduced another Bug (recipes open fullscreen and can't be closed) because I rushed this update a little bit, but that will be fixed in a couple of days. You should at least be able to log in though.

**Comment by riemnafets** [comment]
I can confirm that login via http now works in version 1.8.2 so I‘m now able to play with the app.

Thanks a lot for your support!

**Comment by VincentMeilinger** [comment]
That's great to hear! 
Thank you for your help in resolving this ;)
