### ISSUE TITLE
Interactive number of servings

### ISSUE THREAD

**Issue by Lanjelin** [VincentMeilinger/Nextcloud-Cookbook-iOS#16]
An option to change number of servings, having the ingredients (--> grocery) list update based on number of servings.  
The website UI of NC Cookbook does have this.

I imagine it would possibly be as simple as: `recipe-ingredient / recipe-servings * app-servings = app-ingredient`  
No experience with iOS development, or I'd make a PR

**Comment by VincentMeilinger** [comment]
Hey, thanks for the suggestion!
I definitely plan to implement that at some point, but it might take a while since I‘m a little busy at the moment. I will add your suggestion to the planned feature list for now.

**Comment by VincentMeilinger** [comment]
Resolved in #21
