### ISSUE TITLE
No content although cookbook contains recipes

### ISSUE THREAD

**Issue by schwantuschke** [VincentMeilinger/Nextcloud-Cookbook-iOS#23]
After the sync, I have cookbooks that contain recipes. The number is also displayed correctly in the cookbook overview. However, no recipes are displayed. Pressing Update does not help either.

![IMG_D702F8CC7FA7-1](https://github.com/VincentMeilinger/Nextcloud-Cookbook-iOS/assets/4090141/0963975c-6fcb-437d-909e-f9727725941d)

**Comment by schwantuschke** [comment]
The sync seems to have problems with certain characters. For example, all recipes in a cookbook are not loaded if a recipe contains an Ü or á or ê.
If I move them to another cookbook then the recipes from the previous cookbook load. If I move it back, I can see the other recipes, but not the ones with the special character.

**Comment by VincentMeilinger** [comment]
Hey @schwantuschke, 
Thanks for pointing this out! There are indeed decoding issues when loading the recipes. This issue will be fixed in the next update, which is coming soon!

**Comment by VincentMeilinger** [comment]
Hey @schwantuschke, 
does update 1.10.1 fix your issue? It should be downloadable right now.

**Comment by schwantuschke** [comment]
Now it works. Thanks

**Comment by schwantuschke** [comment]
Now it works. Thanks
