### ISSUE TITLE
[Feature] Mass import from Paprika 3 export

### ISSUE THREAD

**Issue by mobrien03** [VincentMeilinger/Nextcloud-Cookbook-iOS#26]
I have 83 recipes exported from Paprika 3 which I would like to be able to import into the Cookbook-iOS app.   It would be great if you would consider this feature on your roadmap. Thanks!

**Comment by VincentMeilinger** [comment]
Hey @mobrien03, 

At this time, I don't have plans to develop a 'mass import' feature except (maybe) for websites that conform to the schema.org recipe format. Integrating support for importing other recipe formats would be beyond what I can currently manage.

However, you may not need this feature anyway:
I'll assume you refer to the "Paprika Recipe Manager" app. In case I'm mistaken, feel free to correct me. 
It looks like this app supports the export of recipes. If there is an option to export your recipes in `.json` format, there is a good chance that you can simply drop them in the recipe folder of your Nextcloud instance. If you refresh the Cookbook app, your recipes should show up. However, if your recipes are only exportable as PDFs, you'll need to manually transfer them unfortunately.
