### ISSUE TITLE
Importing recipes from web sites

### ISSUE THREAD

**Issue by VincentMeilinger** [VincentMeilinger/Nextcloud-Cookbook-iOS#6]
Users should be able to import recipes from websites. This could be achieved by scraping the recipe site for schema.org json recipe data.

**Comment by sowmyavyk** [comment]
Can you provide more info about the issue.

**Comment by VincentMeilinger** [comment]
Sure. 
It would be nice if users could import recipes from websites (e.g. [allrecipes.com](https://www.allrecipes.com)), to store them in their personal cloud and in this app. This feature is already present in the Nextcloud Cookbook cloud service, but having this functionality integrated in this app would be nice.
The recipe schema of Nextcloud Cookbook follows the [schema.org recipe specification](https://schema.org/Recipe), and some recipe websites provide the recipe data in the same schema (as JSON data). This commonality makes it feasible to develop a "scraper" that can capture recipe data when users provide a link to a desired recipe website.
Unfortunately, I am unsure about how many websites follow the schema, so the success rate of the scraper would be uncertain. However, for the majority of websites I personally use, schema compliance is given, making this feature preferable to manual recipe copying.
